apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: service-spawner
    app: this-service
    version: base
  name: this-service
  namespace: this-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: this-service
      version: base
  template:
    metadata:
      labels:
        project: service-spawner
        app: this-service
        version: base
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - while sleep 0.1; do wget -q $TARGET; done
        image: busybox
        imagePullPolicy: IfNotPresent
        name: client
        env:
        - name: TARGET
          value: "target-service:8080"
      - image: nginxdemos/nginx-hello:0.2
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: this-service
  namespace: this-namespace
  labels:
    project: service-spawner
    app: this-service
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: this-service
